version: '3.9'

services:
  db:
    image: postgres:17.4
    container_name: schedule-postgres
    restart: unless-stopped
    env_file:
      - src/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7.2
    container_name: schedule-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: schedule-bot-rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - src/.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build: .
    container_name: schedule-bot-taskiq-worker
    restart: always
    env_file:
      - src/.env
    command: >
      taskiq worker core:broker
      --fs-discover
      --tasks-pattern "**/tasks/*.py"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  scheduler:
    build: .
    container_name: schedule-bot-taskiq-scheduler
    restart: always
    env_file:
      - src/.env
    command: >
      taskiq scheduler core:scheduler tasks.schedule
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  bot:
    build: .
    container_name: schedule-bot
    restart: unless-stopped
    env_file:
      - src/.env
    command: >
      sh -c "
        echo 'Running migrations...';
        alembic upgrade head;
        python -m bot.main;
      "
    volumes:
      - ./src/alembic/versions:/app/alembic/versions
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: